DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE CATE;
DROP TABLE SELLER;
DROP TABLE PRODUCT;
DROP SEQUENCE REVIEW_SEQ;
DROP TABLE REVIEW;
DROP TABLE PURCHASE;

DROP TABLE CART;

CREATE TABLE CUSTOMER(
    CID VARCHAR2(50) PRIMARY KEY,
    CPW VARCHAR2(50) NOT NULL,
    CNAME VARCHAR2(50),
    CEMAIL VARCHAR2(250) NOT NULL,
    CMOBILE VARCHAR2(50) NOT NULL,
    CADDR VARCHAR2(250),
    CANNIVERSARY DATE, 
    CRDATE DATE
);

CREATE TABLE CATE(
    CATEID VARCHAR2(50) PRIMARY KEY,
    CATENAME VARCHAR2(50) NOT NULL
);

CREATE TABLE SELLER(
    SID VARCHAR2(50) PRIMARY KEY,
    SPW VARCHAR2(50) NOT NULL,
    SACCOUNT VARCHAR2(250) NOT NULL
);

CREATE TABLE PRODUCT(
    PID VARCHAR2(50) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    PPRICE NUMBER(7) NOT NULL,
    PSTOCK NUMBER(7) NOT NULL,
    PCONTENT VARCHAR2(4000) NOT NULL,
    PRDATE DATE NOT NULL,
    CATEID VARCHAR2(50) REFERENCES CATE(CATEID),
    SID VARCHAR2(50) REFERENCES SELLER(SID)
);

CREATE SEQUENCE REVIEW_SEQ
    MAXVALUE 9999999
    NOCACHE
    NOCYCLE;



