DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SEQ MAXVALUE 9999 NOCYCLE NOCACHE;
CREATE TABLE FRIEND (
    NO NUMBER(4),
    NAME VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    PRIMARY KEY(NO)
);

INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'È«±æµ¿', '010-9999-9999');
SELECT * FROM FRIEND;

COMMIT;

SELECT * FROM FRIEND WHERE NAME LIKE '%'||'¹Ú'||'%' AND PHONE LIKE '%'||'010'||'%';