SELECT*FROM EMP;

SELECT*FROM (SELECT ROWNUM RN, A.* FROM (SELECT*FROM EMP) A) WHERE RN BETWEEN 2 AND 3;

SELECT COUNT(*) TOTCNT FROM EMP;

SELECT*FROM EMP WHERE ENAME LIKE '%'||'A'||'%' AND JOB LIKE '%'||'E'||'%';