DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    ID VARCHAR2(30) PRIMARY KEY NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30),
    BIRTH DATE NOT NULL,
    RDATE DATE NOT NULL,
    ADDRESS VARCHAR2(200));


-- 회원리스트
SELECT * FROM MEMBER;

-- 회원가입
INSERT INTO MEMBER (ID,PW,NAME,EMAIL,BIRTH,RDATE,ADDRESS) VALUES ('ccc','111','박','AAA@BB.CC','1990-01-01',SYSDATE,'서울');

COMMIT;
