CREATE SEQUENCE MEMBER_DUMMY_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;

-- 회원가입
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES (MEMBER_DUMMY_SEQ.NEXTVAL||'a', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
