DROP TABLE MVC_MEMBER;

CREATE TABLE MVC_MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mPW VARCHAR2(30) NOT NULL,
    mNAME VARCHAR2(30) NOT NULL,
    mEMAIL VARCHAR2(30),
    mPHOTO VARCHAR2(30) DEFAULT 'NOIMG.JPG' NOT NULL,
    mBIRTH DATE,
    mADDRESS VARCHAR2(300),
    mRDATE DATE DEFAULT SYSDATE
);

-- 아이디 중복체크(mID)
SELECT*FROM MVC_MEMBER WHERE mID='aaa';
-- 회원가입(mID, mPW, mNAME / mEMAIL, mPHOTO, mBIRTH, mADDRESS)
INSERT INTO MVC_MEMBER(mID, mPW, mNAME, mEMAIL, mPHOTO, mBIRTH, mADDRESS)
    VALUES ('aaa', 'aaa', '김갹갹', NULL, 'NOIMG.JPG', NULL, NULL); 
-- 로그인(mID, mPW)
SELECT*FROM MVC_MEMBER WHERE mID='aaa' AND mPW='aaa';
-- 로그인 후 세션에 정보를 넣기 위해 mID로 member dto 가져오기
SELECT*FROM MVC_MEMBER WHERE mID='aaa';
-- 회원 정보 수정(mID)
UPDATE MVC_MEMBER
    SET mPW = 'bbb',
        mNAME = '김갹갹수정',
        mEMAIL = 'aaa@aaa.aaa',
        mPHOTO = 'NOIMG.JPG',
        mBIRTH = '90/01/08',
        mADDRESS = '서울시'
        WHERE mID='aaa';
-- 회원 목록(startRow, endRow)
--- 기준
SELECT*FROM MVC_MEMBER ORDER BY mRDATE DESC;
SELECT*FROM(SELECT ROWNUM RN, A.* FROM (SELECT*FROM MVC_MEMBER ORDER BY mRDATE DESC)A) WHERE RN BETWEEN 2 AND 5;
-- 가입한 전체 회원 수
SELECT COUNT(*) TOTCNT FROM MVC_MEMBER;

COMMIT;