-- 조회속도를 높이기 위한 인덱스 
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT*FROM EMP;
INSERT INTO EMP01 SELECT*FROM EMP01; 
SELECT COUNT(*) FROM EMP01;
DESC EMP01;
INSERT INTO EMP01(EMPNO,ENAME) VALUES (1111,'HONG'); -- 데이터의 1%가 HONG
INSERT INTO EMP01 SELECT*FROM EMP01; -- 12번? 실행 462848row 
SELECT*FROM USER_INDEXES; -- EMP01 테이블과 관련된 인덱스 없음 확인
SELECT*FROM EMP01 WHERE ENAME='HONG'; -- 0.004초 소요
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME); -- ENAME 인덱스 생성
SELECT*FROM EMP01 WHERE ENAME='HONG'; -- 0.002초 소요
INSERT INTO EMP01 SELECT*FROM EMP01; -- 인덱스 만들고 나서 46만행 INSERT 하니까 21초 소요;
DROP INDEX IDX_EMP01_ENAME; -- 인덱스 없앰
INSERT INTO EMP01 SELECT*FROM EMP01; -- 인덱스 없애고 나서 92만행 INSERT 했는데도 4초 소요;
 -- 인덱스를 만들고 INSERT 하면 느려짐 -> 빈번하게 INSERT 하는 경우 INDEX 생성하지마...
