SHOW USER;
SELECT*FROM TAB; -- PARK가 갖고 있는 테이블은 아무것도X
SELECT*FROM SCOTT.EMPV1; -- 테이블이 내거 아닐때는 'USER이름.뷰이름' 해야함
INSERT INTO SCOTT.EMPV1(EMPNO,ENAME,DEPTNO) VALUES (1111,'김',30);
SELECT*FROM SCOTT.EMPV1;
COMMIT;
SELECT*FROM SCOTT.SALGRADE;
INSERT INTO SCOTT.SALGRADE VALUES (6,999,9999);
INSERT INTO SCOTT.SALGRADE VALUES (7,999,9999); 

SELECT * FROM DEPT WHERE DEPTNO=20;