DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
    
CREATE SEQUENCE CNO_SQ
    MAXVALUE 9999
    NOCACHE;

CREATE TABLE CUSTOMER(
    CNO NUMBER(4) PRIMARY KEY,
    CNAME VARCHAR2(50) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(50) UNIQUE,
    POINT NUMBER(20),
    LEVELNO NUMBER(1) REFERENCES CUS_LEVEL(LEVELNO));

INSERT INTO CUS_LEVEL (LEVELNO, LEVELNAME) VALUES (1,'VVIP');
INSERT INTO CUS_LEVEL VALUES (2,'VIP');
INSERT INTO CUS_LEVEL VALUES (3,'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4,'BLACK');

INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNO) VALUES
    (CNO_SQ.NEXTVAL,'È«±æµ¿',TO_DATE('20171017','YYYYMMDD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER VALUES (CNO_SQ.NEXTVAL,'ÀÌÃ¶¼ö',TO_DATE('20171017','YYYYMMDD'),'010-9999-9888',NULL,2);
INSERT INTO CUSTOMER VALUES (CNO_SQ.NEXTVAL,'È«±æ¼ø',TO_DATE('20171017','YYYYMMDD'),'010-9999-7777',50,3);
SELECT *FROM CUSTOMER;

SELECT CNO,CNAME,TO_CHAR(JOINDATE,'YYYY-MM-DD') JOINDATE,PHONE,NVL(POINT,0),LEVELNAME
    FROM CUSTOMER,CUS_LEVEL
    WHERE CUSTOMER.LEVELNO=CUS_LEVEL.LEVELNO;