------------- BOOKKIND / BOOK
CREATE TABLE BOOKKIND (
    BOOKCODE NUMBER(4),
    BOOKKIND VARCHAR2(20),
    LOC VARCHAR2(30),
    PRIMARY KEY(BOOKCODE));

SELECT * FROM BOOKKIND;

INSERT INTO BOOKKIND (BOOKCODE, BOOKKIND, LOC) VALUES
    (100,'철학','3층 인문실');
INSERT INTO BOOKKIND VALUES (200,'인문','3층 인문실');
INSERT INTO BOOKKIND VALUES (300,'자연과학','4층 과학실');
INSERT INTO BOOKKIND VALUES (400,'IT','4층 과학실');

DROP TABLE BOOK;

CREATE TABLE BOOK (
    BOOKCODE NUMBER(4),
    BOOKID VARCHAR2(20),
    BOOKNAME VARCHAR2(30),
    PUBLISHER VARCHAR2(20),
    PUBYEAR NUMBER(10),
    PRIMARY KEY(BOOKID),
    FOREIGN KEY(BOOKCODE) REFERENCES BOOKKIND(BOOKCODE));

SELECT * FROM BOOK;

INSERT INTO BOOK (BOOKCODE,BOOKID,BOOKNAME,PUBLISHER,PUBYEAR) VALUES
    (100,'100A01','철학자의 삶','더존출판',2017);
INSERT INTO BOOK VALUES (400,'400A01','이것이 DB다','더존출판',2018);

------------- MAJOR / STUDENT
CREATE TABLE MAJOR (
    MAJOR_CODE NUMBER(10),
    MAJOR_NAME VARCHAR2(50),
    OFFICE_LOC VARCHAR2(50),
    PRIMARY KEY(MAJOR_CODE));
    
SELECT * FROM MAJOR;

INSERT INTO MAJOR (MAJOR_CODE,MAJOR_NAME,OFFICE_LOC) VALUES
    (1,'경영정보','3층 인문실');
INSERT INTO MAJOR VALUES (2,'소프트웨어','3층 인문실');
INSERT INTO MAJOR VALUES (3,'디자인','4층 과학실');
INSERT INTO MAJOR VALUES (4,'경제','4층 과학실');

DROP TABLE STUDENT;

CREATE TABLE STUDENT(
    HAKBUN VARCHAR2(20),
    NAME VARCHAR2(20),
    SCORE NUMBER(10),
    MAJOR_CODE NUMBER(10),
    PRIMARY KEY(HAKBUN),
    FOREIGN KEY(MAJOR_CODE) REFERENCES MAJOR(MAJOR_CODE)    );
    
SELECT * FROM STUDENT;

INSERT INTO STUDENT (HAKBUN,NAME,SCORE,MAJOR_CODE) VALUES
    ('A01','김길동',100,1);
INSERT INTO STUDENT VALUES ('A02','문길동',100,2);
INSERT INTO STUDENT VALUES ('A03','홍길동',95,1);

