--1
SELECT ENAME,JOB,HIREDATE FROM EMP
    WHERE HIREDATE BETWEEN TO_DATE('19810220','YYYYMMDD') AND TO_DATE('19810501','YYYYMMDD')
    ORDER BY HIREDATE;
--2    
SELECT W.ENAME, W.SAL, W.DEPTNO, DNAME, LOC, NVL(M.ENAME,'없음') 상사명 FROM EMP W, EMP M, DEPT D
    WHERE W.DEPTNO=D.DEPTNO AND W.MGR=M.EMPNO(+);
--3
SELECT ENAME, JOB, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
        AND ENAME LIKE '%L%';
--4        
SELECT EMPNO, ENAME, JOB, SAL, GRADE 
    FROM EMP, SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL 
    ORDER BY SAL DESC;
--5
SELECT EMPNO, ENAME, TO_CHAR(SAL,'$99,999') FROM EMP WHERE DEPTNO=20;
--6
SELECT DNAME, COUNT(*) FROM DEPT D, EMP E 
    WHERE D.DEPTNO=E.DEPTNO
    GROUP BY DNAME
    HAVING COUNT(*)>=5;
--7
SELECT*FROM EMP WHERE (JOB,SAL)=(SELECT JOB,SAL FROM EMP WHERE ENAME='FORD') AND ENAME<>'FORD';
--8 
SELECT ENAME, SAL FROM EMP
    WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');
--1
SELECT EMPNO, ENAME, SAL,DEPTNO FROM EMP E 
    WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);
--2 
DELETE FROM EMP WHERE ENAME='FORD';
--3
UPDATE EMP SET SAL=SAL*1.1 WHERE SAL>=3000;
--4
UPDATE EMP SET DEPTNO=20, JOB='MANAGER' WHERE ENAME='SCOTT';
--5
UPDATE EMP SET SAL=SAL+1000 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
--6
SELECT EMPNO, ENAME, HIREDATE FROM (SELECT ROWNUM RN, EMPNO, ENAME, HIREDATE FROM 
                                        (SELECT*FROM EMP ORDER BY HIREDATE DESC))
                                             WHERE RN BETWEEN 6 AND 10;
--7
COMMIT;


SELECT DNAME, COUNT(*) FROM DEPT D, EMP E WHERE D.DEPTNO=E.DEPTNO GROUP BY DNAME HAVING COUNT(*) >=5;

CREATE SEQUENCE CUS_SQ
    MAXVALUE 9999
    NOCACHE;

UPDATE EMP SET SAL=SAL+1000 WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');
DELETE FROM EMP WHERE ENAME='FORD';

SELECT W.ENAME, W.SAL, W.DEPTNO, DNAME, LOC, NVL(M.ENAME,'없음') 상사명 FROM EMP W, DEPT D, EMP M
    WHERE D.DEPTNO=W.DEPTNO AND W.MGR=M.EMPNO(+);
    
ROLLBACK;

SELECT*FROM EMP;
