-- ※[customerDAO]
-- 아이디 중복 체크
SELECT*FROM CUSTOMER WHERE CID='aaa';
-- 회원 가입
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CGENDER, CBIRTH) 
    VALUES ('aaa','111','전대한','010-9999-9999', NULL, '서울시','m','1990-01-08');
-- 로그인(ID/PW)
SELECT * FROM CUSTOMER WHERE CID='aaa' and CPW='111';
-- 로그인 후 ID로 DTO 가져오기(SESSION에 보관)
SELECT * FROM CUSTOMER WHERE CID='aaa';
-- 정보 수정(ID로 찾아서)
UPDATE CUSTOMER SET CPW='111',
                CNAME='박지영 수정',
                CTEL = '010-9999-1111',
                CEMAIL='a@a.com',
                CADDRESS='서울시 수정',
                CBIRTH=to_date('1990-01-08','yyyy-mm-dd'),
                CGENDER = 'm'
        WHERE CID='aaa';
-- 회원 리스트 보기(startRow부터 endRow까지 목록보기)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM CUSTOMER ORDER BY cID) A) WHERE RN BETWEEN 1 AND 3;
-- 등록된 회원 수 가져오기
SELECT COUNT(*) TOTCNT FROM CUSTOMER;
COMMIT;

-- ※[bookDAO]
-- 책 등록
INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_PRICE, BOOK_IMAGE1, BOOK_IMAGE2, BOOK_CONTENT, BOOK_DISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은자바다', 20000, 'NOTHING.JPG', 'NOTHING.JPG', '좋다', 10);
INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_PRICE, BOOK_IMAGE1,BOOK_CONTENT, BOOK_DISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은JSP다', 21000, 'NOTHING.JPG', '좋다', 10);
INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_PRICE, BOOK_IMAGE2,BOOK_CONTENT, BOOK_DISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은CSS다', 22000, 'NOTHING.JPG', '좋다', 10);
INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_PRICE, BOOK_CONTENT, BOOK_DISCOUNT)
    VALUES (BOOK_SEQ.NEXTVAL, '이것은ORACLE이다', 23000, '좋다', 10);
-- 책 목록(TOP-N) : 페이징
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOOK ORDER BY BOOK_RDATE DESC)A) 
    WHERE RN BETWEEN 2 AND 3;
-- 등록된 책 개수
SELECT COUNT(*) FROM BOOK;
-- BOOK_ID로 책 가져오기
SELECT * FROM BOOK WHERE BOOK_ID='3';
COMMIT;

-- ※[fileboardDAO]
-- 게시글 목록(startRow 부터 endRow 까지) : 페이징
SELECT F.*, CNAME,CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID ORDER BY fREF DESC, fRE_STEP; -- 기준
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT F.*, CNAME, CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID ORDER BY fREF DESC, fRE_STEP )A) 
    WHERE RN BETWEEN 2 AND 10;
-- 글 수 가져오기
SELECT COUNT(*) TOTCNT FROM FILEBOARD;
-- 원글 쓰기 insert(fileboardDto )
INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa', '제목', '내용', '파일이름', '111', FILEBOARD_SEQ.CURRVAL, 0, 0, '111.111.11.11');
-- 답변글 쓰기위한 stepA
UPDATE FILEBOARD SET fRE_STEP=fRE_STEP+1 WHERE fREF=2 AND fRE_STEP>0;
-- 답변글 쓰기 insertReply(fileboardDto reply)
INSERT INTO FILEBOARD (fNUM, cID, fSUBJECT, fCONTENT, fFILENAME, fPW, fREF, fRE_STEP, fRE_LEVEL, fIP)
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'aaa', '제목', '내용', '파일이름', '111', 2, 0+1, 0+1, '111.111.11.11');
SELECT F.*, C.CNAME FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID ORDER BY fREF DESC, fRE_STEP;
-- 히트 수 올리기
UPDATE FILEBOARD SET fHIT=fHIT+1 WHERE fNUM=5;
-- 글 상세보기 fileboardDto getDtail(int fnum)
SELECT F.*, C.CNAME, C.CEMAIL FROM FILEBOARD F, CUSTOMER C WHERE F.CID=C.CID AND fNUM=3;
-- 글 수정하기 modify(int fnum)
UPDATE FILEBOARD SET fSUBJECT = '바꾼 제목', fCONTENT = '바꾼 내용', fFILENAME = '바꾼 파일', fPW ='111', fIP='123.123.1.1' WHERE fNUM='2';
SELECT*FROM FILEBOARD WHERE fNUM=2;
-- 글 삭제  delete(int fnum, String fpw)
DELETE FROM FILEBOARD WHERE fNUM=10 AND fPW='111';